### ISSUE TITLE
Not able to use assembly .AddNamespace

### ISSUE THREAD

**Issue by JasonFoglia** [volkovku/RazorTemplates#14]
Html5 is a separate project. 

var template = Template.WithBaseType<TemplateBase>()
                       .AddNamespace("Html5")
                       .Compile("@Html5.Tag.Create(\"div\", \"test\")"); // Fails

error CS0246: The type or namespace name 'Html5' could not be found (are you missing a using directive or an assembly reference?)

There is a reference to the project and there is a using directive at the top of the code.

**Comment by lvermeulen** [comment]
@Jason54 @Eibwen @volkovku I needed this and it was actually pretty easy to fix. If anyone is still interested, I can add a PR although the project no longer seems active.

**Comment by volkovku** [comment]
@lvermeulen thanks for you interest. Unfortunately in last years I have no time to support this project. But I can review and merge you pull request.

**Comment by lvermeulen** [comment]
@volkovku That's great! PR submitted.
